version: "3.9"
services:
  gateway:
    image: gateway
    ports:
      - "8080:80"
    environment:
      - RESERVATION=reservation:80
      - PAYMENT=payment:80
      - LOYALTY=loyalty:80

  reservation:
    image: reservation
    ports:
      - "8070:80"
    environment:
      - DBHOST=postgres2
      - DBPORT=5432
      - DATABASE=reservations
      - USERNAME=program
      - PASSWORD=test

  payment:
    image: payment
    ports:
      - "8060:80"
    environment:
      - DBHOST=postgres2
      - DBPORT=5432
      - DATABASE=payments
      - USERNAME=program
      - PASSWORD=test

  loyalty:
    image: loyalty
    ports:
      - "8050:80"
    environment:
      - DBHOST=postgres2
      - DBPORT=5432
      - DATABASE=loyalties
      - USERNAME=program
      - PASSWORD=test

  postgres2:
    image: library/postgres:13
    container_name: postgres2
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "54321:5432"

volumes:
  db-data: